### PR TITLE
Add template option

### PR DESCRIPTION
**Pull request by weixuanfu**
Add a parameter called `template` in TPOTClassifier/TPOTRegressor for specify pipeline structure.

For now only linear pipeline is supported and I will add support for tree structure later.

- 4 major classes of operators can be used in the template: Selector, Transformer, Classifier, Regressor
- Any operators in [TPOT configuration](http://epistasislab.github.io/tpot/using/#built-in-tpot-configurations) or customized configuration can be used in the template. 
- Template examples: 
     - a. "Selector-Transformer-Classifier": step 1 feature selection; step 2. data transformation; step 3 calssification
     - b. "SelectPercentile-Transformer-Classifier" step 2 and step 3 are the same with  example a above, where tpot will randomly chose transfomer/classsifier for step2/step3. The only difference is the step 1 is specified as [SelectPercentile](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectPercentile.html)

Demos:

```
# coding: utf-8
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
# MISIT dataset
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)
# example a
tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='Selector-Transformer-Classifier')
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

# example b
tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='SelectPercentile-Transformer-Classifier')
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))


```

### CODE REVIEW

**Comment by weixuanfu** [comment]
Update: Allow CombineDFs in template for initial tree-structure support. Demo:

```
tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='SelectPercentile-CombineDFs-Transformer-Classifier')
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

```
The pipeline will be like
```
SelectPercentile--
                            --Transformer-Classifier
SelectPercentile--
```

**Comment by lelaboratoire** [comment]
Will the number of "SelectPercentile" operators be optimized with TPOT for this initial tree-structure?

**Comment by weixuanfu** [comment]
```python
from tpot import TPOTClassifier
import numpy as np
import pandas as pd
from tpot.config import classifier_config_dict
test_data = pd.read_csv("tests/tests.csv")
test_X = test_data.drop("class", axis=1)
test_y = test_data['class']
classifier_config_dict['tpot.builtins.DatasetSelector'] = {
    'subset_dir': ['tests/test_subset_dir'],
    'sel_subset_fname': ['test_subset_1.snp' ,'test_subset_2.snp']
}

tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='DatasetSelector-CombineDFs-Transformer-Classifier',
                           config_dict=classifier_config_dict)
tpot.fit(test_X, test_y)
```
The codes above works but I think I need refine `DatasetSelector` for universal application.

**Comment by weixuanfu** [comment]
Install scikit-rebate via:
```shell
pip install --upgrade --no-deps --force-reinstall git+https://gith
ub.com/weixuanfu/scikit-rebate.git@add_transformix
```
It has a fix for supporting scikit-learn API (I will fix this later in the future version of scikit-rebate).


- select 1 dataset demo
```python
from tpot import TPOTClassifier
import numpy as np
import pandas as pd
from tpot.config import classifier_config_dict
test_data = pd.read_csv("tests/tests.csv")
test_X = test_data.drop("class", axis=1)
test_y = test_data['class']
# in the subset_test.csv there are 3 subsets 
classifier_config_dict['tpot.builtins.DatasetSelector'] = {
    'subset_list': ['tests/subset_test.csv'],
    'sel_subset': [0,1]
}

classifier_config_dict['skrebate.MultiSURF'] = {
        'n_features_to_select': range(1, 5)
    }

tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='DatasetSelector-MultiSURF-Transformer-Classifier',
                           config_dict=classifier_config_dict)
tpot.fit(test_X, test_y)
```
- select 2 datasets demo
```
from tpot import TPOTClassifier
import numpy as np
import pandas as pd
from tpot.config import classifier_config_dict
from itertools import combinations
test_data = pd.read_csv("tests/tests.csv")
test_X = test_data.drop("class", axis=1)
test_y = test_data['class']

# in the subset_test.csv there are 3 subsets 
classifier_config_dict['tpot.builtins.DatasetSelector'] = {
    'subset_list': ['tests/subset_test.csv'],
    'sel_subset': list(combinations(range(3), 2)) # make all possible combinations for all subsets 
}
classifier_config_dict['skrebate.MultiSURF'] = {
        'n_features_to_select': range(1, 5)
    }

tpot = TPOTClassifier(generations=5, 
                           population_size=50, verbosity=2, 
                           template='DatasetSelector-MultiSURF-Transformer-Classifier',
                           config_dict=classifier_config_dict)
tpot.fit(test_X, test_y)
```

**Comment by adrose** [comment]
Will this branch be making it into master? What is the latest with the template design?

**Comment by weixuanfu** [comment]
Hi, @adrose we will merge template it into master after more tests.

Please check this [comment](https://github.com/weixuanfu/tpot/pull/2#issuecomment-429986077) for latest usage of template function. 

If you prefer use rebate methods with template, please install a dev version of skrebate via:

```
pip install --upgrade --no-deps --force-reinstall git+https://gith
ub.com/weixuanfu/scikit-rebate.git@add_transformix
```
Then you can add those rebate methods to the default configuration dictionary, like:

```python
classifier_config_dict['skrebate.MultiSURF'] = {
        'n_features_to_select': range(1, 5)
    }
``` 

More details about customizing operators and parameters in TPOT, please check this [link](https://epistasislab.github.io/tpot/using/#customizing-tpots-operators-and-parameters)

**Pull request merged**
